Module6 task1
htmlacademy-react/2486081-six-cities-16 pull request #6
Opened 2024-08-13 14:02 UTC by RnizereB

2024-08-13 15:49 UTC, baileys-li requested changes
А поправь билд. Там старые пропсы ты передаёшь, которые теперь не нужны

2024-08-13 15:49 UTC, baileys-li commented on src/store/reducer.ts
> +  initialData: initialData['Paris']
странный нейминг для стора

2024-08-13 19:45 UTC, RnizereB commented on src/store/reducer.ts
> +  initialData: initialData['Paris']
А какой должен быть? Не совсем понимаю, что конкретно должно находится в сторе.

2024-08-14 18:06 UTC, baileys-li commented on src/store/reducer.ts
> +  initialData: initialData['Paris']
Можно просто `offers` и `allOfers`, `entities` и т.д.
Удали не используемые пропсы, чтобы приложение могло сбилдится.
А так всё ок

2024-08-17 09:59 UTC, merged